import { Room, RoomEvent, Track } from 'https://cdn.jsdelivr.net/npm/livekit-client@2.15.6/+esm';

const status=document.querySelector('#status'), transcript=document.querySelector('#transcript'), connectButton=document.querySelector('#connect'), disconnectButton=document.querySelector('#disconnect'), stageMessage=document.querySelector('#stage-message'), statePill=document.querySelector('#state-pill'), result=document.querySelector('#result'), scenarios=document.querySelector('#scenarios'), latencyReadout=document.querySelector('#latency-readout');
let room,callId,lastUserFinalAt=0,awaitingFirstAudio=false;
const copy={ready:['Ready to connect','Press start when you’re ready to speak.'],connecting:['Connecting','Joining your private voice session…'],connected:['Listening','Luma is listening. Go ahead.'],listening:['Listening','Luma is listening. Go ahead.'],thinking:['Thinking','Luma is checking that for you…'],speaking:['Luma is speaking','You can interrupt naturally at any time.'],disconnected:['Call ended','Start a new conversation whenever you’re ready.']};
function state(value){const key=String(value).toLowerCase();const [label,message]=copy[key]||[value,''];document.body.dataset.callState=key;status.textContent=label;stageMessage.textContent=message;statePill.dataset.state=key;}
function line(who,text){const empty=transcript.querySelector('.empty-state');if(empty)empty.remove();const row=document.createElement('div');row.className='transcript-line';row.dataset.speaker=who;const tag=document.createElement('span');tag.className='speaker-tag';tag.textContent=who==='Luma'?'L':'Y';const p=document.createElement('p');p.className='transcript-copy';const strong=document.createElement('strong');strong.textContent=`${who} `;p.append(strong,document.createTextNode(text));row.append(tag,p);transcript.append(row);transcript.scrollTop=transcript.scrollHeight;}
function resetTranscript(){transcript.replaceChildren();const empty=document.createElement('div');empty.className='empty-state';empty.innerHTML='<span>✦</span><p>Your conversation appears here in real time.</p>';transcript.append(empty);}
async function recordFirstAudio(){if(!awaitingFirstAudio||!lastUserFinalAt)return;awaitingFirstAudio=false;const ms=Math.round(performance.now()-lastUserFinalAt);latencyReadout.textContent=`First-audio latency: ${ms} ms`;try{await fetch('/telemetry/voice-latency',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({call_id:callId,end_of_speech_to_audio_ms:ms})})}catch{latencyReadout.textContent=`First-audio latency: ${ms} ms (not recorded)`}}
connectButton.onclick=async()=>{try{state('connecting');connectButton.disabled=true;callId=crypto.randomUUID();latencyReadout.textContent='First-audio latency will appear after your first reply.';const response=await fetch('/token',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({participant_name:'Web guest'})});if(!response.ok)throw new Error((await response.json()).detail||'Token request failed');const {server_url,participant_token}=await response.json();room=new Room({adaptiveStream:true,dynacast:true});room.on(RoomEvent.TrackSubscribed,(track)=>{if(track.kind===Track.Kind.Audio){const audio=track.attach();audio.className='remote-audio';document.body.append(audio);}});room.on(RoomEvent.ActiveSpeakersChanged,speakers=>{if(speakers.some(participant=>participant.isAgent))recordFirstAudio()});room.on(RoomEvent.TranscriptionReceived,(segments,participant)=>segments.forEach(s=>{if(!s.final)return;line(participant?.isAgent?'Luma':'You',s.text);if(!participant?.isAgent){lastUserFinalAt=performance.now();awaitingFirstAudio=true;}}));room.on(RoomEvent.ConnectionStateChanged,s=>state(s==='connected'?'listening':s));room.on(RoomEvent.Disconnected,()=>{state('disconnected');connectButton.disabled=false;disconnectButton.disabled=true;});await room.connect(server_url,participant_token);await room.localParticipant.setMicrophoneEnabled(true);disconnectButton.disabled=false;state('listening');line('System','Connected to Luma.');}catch(error){state('ready');stageMessage.textContent=`Could not connect: ${error.message}`;connectButton.disabled=false;}};
disconnectButton.onclick=()=>room?.disconnect();document.querySelector('#clear-transcript').onclick=resetTranscript;
const request=async(path,options={})=>{const r=await fetch(path,options);return{method:options.method||'GET',path,status:r.status,body:await r.json()}};const json=(body,headers={})=>({method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});const create=(key,body)=>request('/reservations',json(body,{'Idempotency-Key':key}));const reset=()=>request('/admin/reset',{method:'POST'});
const cases={T1:async()=>[await reset(),await request('/availability?date=2026-08-14&time=18:00&party_size=4'),await create('play-t1',{name:'Jordan Lee',phone:'310-555-0199',date:'2026-08-14',time:'18:00',party_size:4,notes:null})],T2:async()=>[await reset(),await request('/availability?date=2026-08-14&time=18:30&party_size=4'),await create('play-t2',{name:'Taylor Kim',phone:'424-555-0188',date:'2026-08-14',time:'19:30',party_size:4})],T3:async()=>[await reset(),await request('/availability?date=2026-08-15&time=18:30&party_size=4'),await create('play-t3',{name:'Casey Brown',phone:'213-555-0114',date:'2026-08-15',time:'18:30',party_size:4})],T4:async()=>{const out=[await reset(),await request('/reservations/search?confirmation_code=LUMA-4821')];out.push(await request(`/reservations/${out[1].body.results[0].reservation_id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({time:'19:30',party_size:4})}));return out},T5:async()=>[await reset(),await request('/reservations/search?confirmation_code=LUMA-4821'),await request('/reservations/res_existing_4821/cancel',{method:'POST'})],T6:async()=>[await reset(),await request('/availability?date=2026-08-16&time=18:00&party_size=2'),await request('/availability?date=2026-08-16&time=18:00&party_size=2')],T7:async()=>{const body={name:'Morgan Reed',phone:'310-555-0166',date:'2026-08-14',time:'20:00',party_size:2};return[await reset(),await create('play-same-key',body),await create('play-same-key',body)]}};
Object.entries(cases).forEach(([id,run])=>{const button=document.createElement('button');button.className='scenario';button.textContent=id;button.title=`Run ${id}`;button.onclick=async()=>{document.querySelectorAll('.scenario').forEach(b=>b.classList.remove('is-running'));button.classList.add('is-running');result.textContent=`Running ${id}…`;try{const calls=await run();const pass=calls.every(c=>c.status<500)&&(id!=='T6'||calls[1].status===503&&calls[2].status===200);result.textContent=`${pass?'PASS':'CHECK'} ${id}\n\n${JSON.stringify(calls,null,2)}`}catch(error){result.textContent=`ERROR ${error.message}`}finally{button.classList.remove('is-running')}};scenarios.append(button)});
document.querySelector('#reset').onclick=async()=>{const r=await reset();result.textContent=`Mock data reset\n\n${JSON.stringify(r,null,2)}`};document.querySelector('#metrics').onclick=async()=>{const r=await request('/admin/metrics');result.textContent=`Operational metrics (no PII)\n\n${JSON.stringify(r.body,null,2)}`};
